### ISSUE TITLE
Investigate: Throwing on lossy insertion

### ISSUE THREAD

**Issue by kolodny** [googleapis/nodejs-bigtable#102]
Currently if we add a boolean or double we lose information on the bigtable side since we can't properly encode the data. Some exploration needs to happen regarding how to go about resolving this issue.

Some ideas

1. Require the user to provide a encoder/decoder when instantiating Bigtable if they use an "unsafe" value:
    ```js
    const bigtable = const bigtable = new Bigtable({
      bufferConverter: new ThingWithEncodeAndDecodeMethod(),
    });
    ....
    table.insert({
      key: `someKey`,
      data: {
        [COLUMN_FAMILY_NAME]: {
          foo: 1.23,
          bar: true
        },
      },
    })
    ```
1. Only allow int64, buffers, (and strings?), and require the user to convert and deconvert to those types:
    ```js
    const coder = new ThingWithEncodeAndDecodeMethod()
    table.insert({
      key: `someKey`,
      data: {
        [COLUMN_FAMILY_NAME]: {
          foo: coder.encode(1.23),
          bar: coder.encode(true)
        },
      },
    });

    const [rows] = table.getRows();
    for (const row of rows) {
      const foo = coder.decodeDouble(row.data.foo)
      const bar = coder.decodeBoolean(row.data.bar)
    }

    ```

**Comment by moander** [comment]
One key question is what the responsibility of this library should be. Is it a connector library that should only support what is supported by the backend or should it also be for the general NodeJS user that want's to store javascript objects.

I like your first approach as it opens up for being both by having a built-in Javascript converter

**Comment by sduskis** [comment]
The back end doesn't support any types whatsoever.  (With the exception of Increment, which requires the user to use big-endian int64)

**Comment by sduskis** [comment]
@kolodny: Does resolving this issue block beta?

**Comment by kolodny** [comment]
I don't think so, if a client suspects they'll need to use large numbers, they would set decode to false and do it by hand. We may want to make decode false by default but that may be a larger discussion

**Comment by moander** [comment]
I'm using msgpack as encoder/decoder. To be able to provide these methods to bigtable would be awesome.

**Comment by sduskis** [comment]
@moander: can you please clarify what you mean?

**Comment by moander** [comment]
@sduskis  I mean that suggestion 1 `Require the user to provide a encoder/decoder when instantiating Bigtable` by @kolodny  is a good fit for how I use nodejs-bigtable so I vote for that.

**Comment by sduskis** [comment]
@kolodny, I'm going to close this.  Pleas reopen if this is still a concern.

**Comment by sduskis** [comment]
We can't figure out how to convert on a read from what ever a value is to a user's type for any given column family / qualifier, since Bigtable doesn't have type metadata.  We'll need an `coder.decode(row.data)`, which is easier for a user to do manually.

I don't see a clean way for this encoder to work at this point, so I'm going to close thise.
