### ISSUE TITLE
Cloud Bigtable should have a gRPC channel pool

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-bigtable#1131]
Copying from https://github.com/googleapis/gax-nodejs/issues/163 (I'll close the corresponding google-gax issue):

> To avoid hitting single-channel limits, the client should leverage a channel pool.

Please consider this feature request or feel free to close if it's not something you're going to implement. Thank you!

**Comment by danieljbruce** [comment]
I recall this was added in https://github.com/googleapis/nodejs-bigtable/blob/main/src/index.ts#L452 long ago. Is this what you mean?
