### ISSUE TITLE
Read the data of one property from 

### ISSUE THREAD

**Issue by artman** [googleapis/nodejs-bigtable#1151]
I'm trying to stream a large amount of data for processing using:
```
table.createReadStream({prefix: `prefix`}).on("data", row => {
  ...
})
```
I'm receiving a lot of rows, but each of them contains only small amounts of pre-serialized data. I'm having a hard time trying to figure out how to receive only the data and not the full row object. What I receive for each data callback is an object representation of the row, containing Bigtable, Table and Instance metadata:

```
 Row {
   bigtable: Bigtable {
     customEndpoint: undefined,
     options: {
       BigtableClient: [Object],
       BigtableInstanceAdminClient: [Object],
       BigtableTableAdminClient: [Object]
     },
     api: { BigtableClient: [BigtableClient] },
     auth: GoogleAuth {
       ...AbortSignal
     },
     projectId: '...',
     appProfileId: undefined,
     projectName: 'projects/{{projectId}}',
     shouldReplaceProjectIdToken: true
   },
   table: Table {
     bigtable: Bigtable {
       customEndpoint: undefined,
       options: [Object],
       api: [Object],
       auth: [GoogleAuth],
       projectId: '...',
       appProfileId: undefined,
       projectName: 'projects/{{projectId}}',
       shouldReplaceProjectIdToken: true
     },
     instance: Instance {
       bigtable: [Bigtable],
       id: '...',
       name: '....'
     },
     name: '...',
     id: '...'
   },
   id: '...',
   data: { entity: { properties: [Array] } }
}
```

Even if this information is not transmitted over the network for every request, it seems wasteful to construct an object for every row when I'm only interested in the data. Any way to omit this metadata and just stream the the data I'm interested in?

**Comment by danieljbruce** [comment]
When the row constructor is called at https://github.com/googleapis/nodejs-bigtable/blob/8cc17aa2acb2540b4c2b233c4245021815a7b030/src/table.ts#L922 the table and bigtable properties that you see are added at https://github.com/googleapis/nodejs-bigtable/blob/8cc17aa2acb2540b4c2b233c4245021815a7b030/src/row.ts#L166-L167.

I don't think this object construction adds very much latency so would it be fine if you just filtered the rows as they were coming in?

```
table.createReadStream({prefix: `prefix`}).on("data", row => {
  const filteredRow = {id: row.id, data: row.data};
});
```

**Comment by danieljbruce** [comment]
In your case I would just create this `filteredRow` object from the streaming data. Feel free to reopen if that doesn't meet your needs.
