### ISSUE TITLE
Comment missing or uses incorrect param

### ISSUE THREAD

**Issue by AVaksman** [googleapis/nodejs-bigtable#119]
The following functions either missing or use incorrect `@param`

| Page Address | Comment Discrepancy |
| --------------- | -------------------------|
|[	create(options,callback)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/cluster.js#L132	)|	callback not in comment param	|
|[	get(gaxOptions,callback)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/cluster.js#L240	)|	callback not in comment param	|
|[	create(options,callback)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/family.js#L161	)|	callback not in comment param	|
|[	create(options, callback)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/instance.js#L86	)|	callback not in comment param	|
|[	save(entry, gaxOptions, callback)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/row.js#L903	)|	Comment param is written as key instead of entry	|
|[	create(options, callback)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/table.js#L159	)|	callback not in comment param	|
|[	_flush(cb)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/chunktransformer.js#L101	)|	callback function name is cb but comment has it as callback	|
|[	destroy(err)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/chunktransformer.js#L119	)|	parameter is err but comment its mentioned as error	|
|[	all(pass)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/filter.js#L237	)|	comment doesn't have details of param	|
|[	column(column)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/filter.js#L360	)|	comment doesn't have details of param	|
|[	condition(condition)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/filter.js#L436	)|	comment doesn't have details of param	|
|[	family(family)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/filter.js#L459	)|	comment doesn't have details of param	|
|[	interleave(filters)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/filter.js#L502	)|	comment doesn't have details of param	|
|[	label(label)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/filter.js#L528	)|	comment doesn't have details of param	|
|[	row(row)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/filter.js#L635	)|	comment doesn't have details of param	|
|[	sink(sink)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/filter.js#L729	)|	comment doesn't have details of param	|
|[	time(time)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/filter.js#L746	)|	comment doesn't have details of param	|
|[	value(value)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/filter.js#L855	)|	comment doesn't have details of param	|
|[	convertFromBytes(bytes, options)	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/mutation.js#L64	)|	comment doesn't have options in param description	|
|[	parse(mutation) 	](	https://github.com/googleapis/nodejs-bigtable/blob/df980606728c31c9c0f18af8d40358747757184c/src/mutation.js#L292	)|	Comment uses param as entry instead of mutation	|

**Comment by sduskis** [comment]
https://github.com/googleapis/nodejs-bigtable/blob/master/src/table.js#L208 should be options.rule instead of just rule.

**Comment by sduskis** [comment]
This was fixed by #136
