### ISSUE TITLE
Can not read large row from Bigtable Stream

### ISSUE THREAD

**Issue by Turniii** [googleapis/nodejs-bigtable#122]
Hello,

I am having an issue reading bigtable rows from stream.
My rows are constantly growing while I receive new data. 
Now the size of some rows have exceeded the maximum authorized and I am getting the following error message: 

Error: 8 RESOURCE_EXHAUSTED: Received message larger than max (4411510 vs. 4194304)

Is there a way to stream such messages ? I am using hashed keys and as I can not receive the message, I can not see wich keys are having issue to be read.
```
const bigtableStream = table.createReadStream()
      .on('data', row => {
        // Do Stuff   
      });
      .on('error', err => console.log(err))
```

environement: 
NodeJs: 8.9.4
google-cloud/bigtable: 0.13.1

**Comment by sduskis** [comment]
This is a known problem.  You can do a couple of things to fix this:

1. You should set some kind of garbage collection policy on your table's column families.  You can do this either with the node.js client or with the cbt command line.  Here's the [getting started with cbt guide](https://cloud.google.com/bigtable/docs/quickstart-cbt).  Here's the docs on how to [set a gc policy using cbt](https://godoc.org/google.golang.org/cloud/bigtable/cmd/cbt#hdr-Set_the_GC_policy_for_a_column_family).
Our ["Hello world"](https://github.com/googleapis/nodejs-bigtable/tree/master/samples/hello-world) shows [how you can set gc rules via node.js](https://github.com/googleapis/nodejs-bigtable/blob/master/samples/hello-world/index.js#L37).
NOTE: This will ensure that your table will not have this problem in the long term, but will not take necessarily take effect right away (you might have to wait a couple of days for compaction to occur)

2. You should use the filter option to get the latest value only.  Our "Hello world" also shows [how you can do get the latest value per qualifier](https://github.com/googleapis/nodejs-bigtable/blob/master/samples/hello-world/index.js#L68).

On our end, we need probably need to make a client-side configuration change , similar to this grpc [configuration change in python clients](https://github.com/grpc/grpc/issues/7927).

**Comment by Turniii** [comment]
Yes I have read about compaction and I am using max version and max age but for this particular column family I need all cells values to make analysis. Is there a filter to get as much cells as possible and then get the rest in an other request

**Comment by sduskis** [comment]
I did some more digging, and it looks like there's a [similar issue for writes](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1755).  Node.js doesn't support a method to set the configuration.

@stephenplusplus, @alexander-fenster, @crwilcox: any ideas or confirmation of this problem would be appreciated.

**Comment by sduskis** [comment]
The default grpc setting for max_message_length (the size of incoming messages) is 4MB. 
 Our Java and Go clients override the default to 128MB to accommodate situations like this one.

**Comment by crwilcox** [comment]
Hi @sduskis . 
Do you have a big table instance that would repro this by chance? I am not super familiar with the node gRPC bits, but it would seem the constructor takes options, which is similar to python, and we may have the ability to change the defaults?

```
    // Create a `gaxGrpc` object, with any grpc-specific options
    // sent to the client.
    opts.scopes = this.constructor.scopes;
    opts.max_send_message_length = -1;
    opts.max_receive_message_length = -1;
    var gaxGrpc = gax.grpc(opts);```

**Comment by sduskis** [comment]
@crwilcox: repro cases are tough to build internally, but @Turniii has one. Is there a way for @Turniii to participate in this?  If not, I can ask one of our developers to try to repro.

**Comment by stephenplusplus** [comment]
I sent a PR in #132 that should fix this for users automatically.

@Turniii in the meantime, you can instantiate your Bigtable client like:

```js
const bigtable = new Bigtable({
  'grpc.max_send_message_length': -1,
  'grpc.max_receive_message_length': -1,
});
```

This will remove those limitations 👍

**Comment by Turniii** [comment]
@sduskis sorry this instance contain personal data so I can not share it for testing.
@stephenplusplus Thank you I will try this way !
