### ISSUE TITLE
DEADLINE_EXCEEDED while inserting rows

### ISSUE THREAD

**Issue by Turniii** [googleapis/nodejs-bigtable#135]
Hello,

I am replicating a BigTable Instance. My script insert new rows after making some changes to the data from the old version to the new one. 
The problem is that after a lot of insertion, I am getting the following error : 
```
  { Error: 4 DEADLINE_EXCEEDED: Deadline Exceeded
    at createStatusError (/node_modules/grpc/src/client.js:64:15)
    at ClientReadableStream._emitStatusIfDone (/node_modules/grpc/src/client.js:270:19)
    at ClientReadableStream._receiveStatus (/node_modules/grpc/src/client.js:248:8)
    at /node_modules/grpc/src/client.js:749:12
  code: 4,
  metadata: Metadata { _internal_repr: {} },
  details: 'Deadline Exceeded' }
```
Am I inserting too many rows at the same time, do I need to set a timeout after a certain amount of insertions ?

Environement:
NodeJs: 8.9.4
google-cloud/bigtable: 0.13.1

**Comment by sduskis** [comment]
I suggest that you raise a support ticket to get a timely and accurate diagnosis and solution to this problem.

The Cloud Bigtable team would need your projectId and instanceId to debug this kind of problem, and that ought to come through a support ticket.  Replication adds another level of complexity that would need to be investigated.

**Comment by stephenplusplus** [comment]
Given the above, I'll close this issue.

@sduskis could you direct @Turniii to the correct place to open a support ticket?

**Comment by sduskis** [comment]
The Cloud console has a method of opening a support ticket.  I'm not sure how to do it myself.
