### ISSUE TITLE
name vs. id?

### ISSUE THREAD

**Issue by sduskis** [googleapis/nodejs-bigtable#137]
There are two concepts for which the terms "id" and "name" are used:

1. **Unique Identifier**: A string that uniquely identifies a resource within some namespace.  Examples:  "my-project", "my-instance" or "my-table".
2. **Fully Qualified Identifier**: A fully qualified identifier that uniquely describes a resource which includes the full name space.  Examples: "/project/my-project",  "/project/my-project/instances/my-instance" and  "/project/my-project/instances/my-instance/tables/my-table"

The Cloud Bigtable protobuf objects use the term "id" to describe the Unique Identifier, and the term "name" to describe the Fully Qualified Identifier.

The node.js client uses inconsistent nomenclature: 

- Projects use "id" is the unique identifier and "name" as the fully qualified identifier
- In instances, "name" to describes the Unique Identifier and "id" describes the Fully Qualified Identifier.  ([Instance Code](https://github.com/googleapis/nodejs-bigtable/blob/master/src/instance.js#L40), [Table Code](https://github.com/googleapis/nodejs-bigtable/blob/master/src/table.js#L58)).

When converting node.js variables to proto messages, the [code](https://github.com/googleapis/nodejs-bigtable/blob/master/src/table.js#L1355) looks like:

```
  var reqOpts = {
    -> name: this.id <-,
    deleteAllDataFromTable: true,
  };
```

This type of confusion, I believe, lead to bug #126.

I would like to use the protobuf as the standard for naming.

@kolodny, @stephenplusplus, @theacodes: do you have any thoughts on this subject?

**Comment by stephenplusplus** [comment]
I'm okay to stick with what the proto file declares.

As a side note, "id" and "name" don't seem like the best tokens for distinct concepts :man_shrugging: In other libraries, I assume "id" to be the *complete* name (e.g. `projects/{project}/region/{region}/zones/{zone}/{my-server}`), and "name" to be the user-friendly portion (e.g. "my-server"). Since people usually remember names: "Hi, Solomon!" as opposed to IDs: "Hi, {state issued ID number}!" 😄

**Comment by sduskis** [comment]
@stephenplusplus: I agree that naming is hard.  If we make this change is going to be a breaking change.  We probably need to do that before Beta, and document the heck out of this change.

**Comment by stephenplusplus** [comment]
What's the breaking part? Instance properties other than `metadata` are not meant to be accessed by a user.

**Comment by sduskis** [comment]
@stephenplusplus: I didn't know if this would be a breaking change.  If this is just an internal implementation detail or a public facing API.  If this is a public facing API, then we have to change this before a Beta launch.

@JustinBeckwith, FYI.

**Comment by sduskis** [comment]
PR #169 is related to this issue.
