### ISSUE TITLE
Read Row Format

### ISSUE THREAD

**Issue by Neofield-Dylan** [googleapis/nodejs-bigtable#1378]
Hi,
I using bigtable with nodejs and typescript. I want to type the row response, so when I read the row, I know the data format.
I already understand reading documentation that row is an object with 'data' property with value being an object which can be accessed with [COLUMN_FAMILY_ID][COLUMN_QUALIFIER_ID]. And then, it returns an array of objects with 'value' and 'timestamp' which it's the value for each Cell.

But I not sure what happens when the row does not has a column set. Does the array of cells comes empty ? Or is row.data[COLUMN_FAMILY_ID] a null value or undefined ? Or is row.data[COLUMN_FAMILY_ID][COLUMN_QUALIFIER_ID] null value or undefined ? What's the expected behavior in this situation ?

Another related question is: 
 If I send row.data[COLUMN_FAMILY_ID][COLUMN_QUALIFIER_ID].value = null to bigTable insert function, does it set the column with a cell with value equal to null ? Or is a not set column ?

PS: I think as these questions are more related to this library implementation, It was more appropriate to open the issue here, despite I being a GCP customer and could open an issue there.

If you need any clarifications about my questions, feel free to ask. I hope this help others and maybe the answer could improve this library documentation.

**Comment by danieljbruce** [comment]
The answer to the first question is that if you try to omit the column field or column name when inserting data then you will get an error: `Error: 3 INVALID_ARGUMENT: Error in field 'Entry list' : Error in element #3 : No mutations provided in entry`. The answer to the second question is that if you provide null for the value then the value will be set to the empty string.

Use the following code snippet to try it out yourself if you like:

```
const {Bigtable} = require('@google-cloud/bigtable');
const INSTANCE_ID = "bigtable-instance";
const TABLE_ID = "copytable";

async function test() {
  const bigtable = new Bigtable({});
  // Connect to an existing instance:my-bigtable-instance
  const instance = bigtable.instance(INSTANCE_ID);
  // Connect to an existing table:my-table
  const table = instance.table(TABLE_ID);
  const entries = [
    {
      key: 'gwashington',
      data: {
        follows: {
          jadams: 1,
        },
      },
    },
    {
      key: 'tjefferson',
      data: {
        follows: {
          gwashington: 1,
          jadams: 1,
        },
      },
    },
    {
      key: 'jadams',
      data: {
        follows: {
          gwashington: 1,
          tjefferson: 1,
        },
      },
    },
    {
      key: 'somethingelse',
      data: {
        follows: {
          columnname: null,
        }
      },
    },
  ];
  // await table.createFamily('follows');
  await table.insert(entries);
  // Read a row from my-table using a row key
  const results = await table.getRows();

  console.log(results);
}
test();
```
