### ISSUE TITLE
node.js v6 cleanup

### ISSUE THREAD

**Issue by kolodny** [googleapis/nodejs-bigtable#178]
This is just a checklist of items that should be done in a followup for #158 

- [x] Remove `.js.` on the require calls. Double check with @ofrobots if we want to do this since Ryan lamented not being explicit with `require`s in his video
- [x] Remove any mention of `const self = this` by switching to arrow functions
- [x] Remove `string-format-obj` as a dep
- [x] Remove `create-error-class` as a dep

---

- [ ] Migrate tests to use ES6 targeting nodev6

**Comment by ofrobots** [comment]
> Remove .js. on the require calls. Double check with @ofrobots if we want to do this since Ryan lamented not being explicit with requires in his video

That ship 🛳 has long sailed :). Omitting the extension is now necessary to switch a project to typescript, so I have no objections 👍.

**Comment by sduskis** [comment]
@kolodny, is there more to come, or is this bug done?

**Comment by kolodny** [comment]
The only item left is to migrate the tests over to es6.

**Comment by sduskis** [comment]
@kolodny, I'm going to close this.  Pleas reopen if this is still a concern.
