### ISSUE TITLE
Don't autostringify the rowKey when decode is false

### ISSUE THREAD

**Issue by kolodny** [googleapis/nodejs-bigtable#185]
See https://github.com/googleapis/nodejs-bigtable/issues/171 for more context

The issue at hand is that the library aggressively converts the rowKey buffer to a string even when the user explicitly sets decode to false. This causes issues where the encoding scheme the user is using doesn't match the default scheme of utf8

**Comment by moander** [comment]
I would argue that this is not a feature request but a bug fix that prevents users from breaking all reads to their table.
