### ISSUE TITLE
Lowercase 't' in Bigtable in repo description (and everywhere else)

### ISSUE THREAD

**Issue by mbrukman** [googleapis/nodejs-bigtable#2]
The description for [this GitHub project](https://github.com/googleapis/nodejs-bigtable) currently is:

> Node.js client for Google Cloud BigTable: Google's NoSQL Big Data database service. https://cloud.google.com/bigtable/

which is capitalizing the "T" in Bigtable incorrectly. As this repo will get cloned, the same capitalization will keep getting copied (with no way to push changes to those repos), which will make it difficult that the `t` is intended to be lowercase.

Unfortunately, it's not possible to submit a PR or another change to the subject; it just requires admin-level permissions to edit it (there's no history tracking for that feature, AFAICT).

Can someone with appropriate permissions please fix this? Thanks!

**Comment by lukesneeringer** [comment]
Fixed. Thank you for bringing that up!
