### ISSUE TITLE
Please cut new 'Beta' release

### ISSUE THREAD

**Issue by danoscarmike** [googleapis/nodejs-bigtable#224]
- [x] quality checklist complete (sduskis)
- [x] README updated (sduskis)
- [x] cut release (stephenplusplus)
- [x] CI completes / publish package to npm (auto)
- [x] refresh API reference docs on cloud.google.com (danoscarmike)

**Comment by danoscarmike** [comment]
Open PR for README: https://github.com/googleapis/nodejs-bigtable/pull/223

**Comment by danoscarmike** [comment]
Adding @sduskis to co-ordinate on release notes

**Comment by stephenplusplus** [comment]
@sduskis I'll send a PR that bumps the version to 0.15.0.

**Comment by sduskis** [comment]
Does that change make a 0.15.0 build available in https://www.npmjs.com/?  Also, how do the docs get generated?

**Comment by stephenplusplus** [comment]
After we merge that PR, we'll create a GitHub release (https://github.com/googleapis/nodejs-bigtable/releases/new), which will tag v0.15.0. That triggers a CI build, which ends by publishing to npm.

For docs, I'm honestly not sure about that flow -- @JustinBeckwith?

**Comment by JustinBeckwith** [comment]
I have no idea either 😑 @alexander-fenster?

**Comment by danoscarmike** [comment]
I can trigger the reference docs once the release is cut.

**Comment by alexander-fenster** [comment]
@jmdobry usually took care of publishing the docs after the release is on npm.

**Comment by danoscarmike** [comment]
Reopening to track package release to NPM and regen of API reference docs.

**Comment by stephenplusplus** [comment]
Sample tests are failing, which blocked the release :( https://circleci.com/gh/googleapis/nodejs-bigtable/6920

**Comment by stephenplusplus** [comment]
@justinbeckwith I believe the error says the GCLOUD_PROJECT env var isn't set... did we stop doing that in the Circle config?

**Comment by JustinBeckwith** [comment]
I don't think I changed anything there 🤷‍♂️   @alexander-fenster?

**Comment by alexander-fenster** [comment]
We never used `PROJECT_ID` in samples. Whoever started using this variable, should have added it in CircleCI config.

![image](https://user-images.githubusercontent.com/4015807/42115090-79a6ade4-7ba6-11e8-9d83-f98d111e6ee5.png)

**Comment by alexander-fenster** [comment]
Looks like it was introduced in #205 and was not reviewed by anyone in the team. Nightly testing failed (of course), but nobody cared (of course). So sad.

**Comment by alexander-fenster** [comment]
I'm fixing it in #234.

**Comment by alexander-fenster** [comment]
CI all green now. You can go ahead with releasing the new version.

**Comment by sduskis** [comment]
@alexander-fenster, how can I get updates from the nightly test failures, or otherwise view the results?

**Comment by alexander-fenster** [comment]
The publicly available dashboard is here: https://storage.googleapis.com/long-door-651.appspot.com/nightly/index.html

They all run in CircleCI so basically can be checked there (https://circleci.com/gh/googleapis/workflows/nodejs-bigtable/tree/master shows all workflows, those marked as `tests` are triggered by commits or tags, those marked as `nightly` are nightly builds). The same is true for all other libraries.

@JustinBeckwith might be working on some magic automation for nightly build results aggregation.

**Comment by stephenplusplus** [comment]
Re-released v0.15.0 to trigger CI to publish to npm. Follow along: https://circleci.com/workflow-run/abcf097b-5308-422e-a012-9cb44d9af705

**Comment by stephenplusplus** [comment]
@danoscarmike I believe we're on the doc-updating step :)

**Comment by danoscarmike** [comment]
Doc review complete. I'll submit on Monday morning.

**Comment by sduskis** [comment]
Update: we (as in @danoscarmike and crew) are still working on docs.  There were some complications unrelated to Cloud Bigtable, which are actively being worked on.

**Comment by danoscarmike** [comment]
Docs are now live: https://cloud.google.com/nodejs/docs/reference/bigtable/0.15.x/
