### ISSUE TITLE
Convert API to use GAPIC

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-bigtable#23]
Continuing from Bigtable [Convert grpc APIs to use GAPIC](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1859), Bigtable is the only API left to complete these steps:

- [ ] Bigtable
  - [ ] Generated files are in repo
  - [ ] Handwritten API is using generated API
  - [ ] Passing through `gaxOptions` is available on all requests
  - [x] Automatic projectId insertion works

**Comment by stephenplusplus** [comment]
@kolodny I'm happy to do this conversion effort whenever the time is right, so it follows the patterns of our other APIs that have converted (there are some gotchas, like pre-processing requests and streams for `{{projectId}}` placeholders, and allowing GAX's `callOptions` parameter through). Updating to GAPIC shouldn't have any breaking changes, but before going GA, I'll do a quick run-through of the API to confirm.

I believe we started talking about the conversion after this request: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2763-- have you found a workaround or otherwise demoted that issue in terms of priority? As it stands, request interceptors are not available with either the `GrpcService` class or GAPIC/gax.

**Comment by sduskis** [comment]
I found out that GAPIC would upgrade our protobufjs dependency from 5.* to 6.*, which should give us massive performance gains.  I'm looking forward to this change.

**Comment by stephenplusplus** [comment]
Are we ready to switch over yet?

**Comment by sduskis** [comment]
We'll be ready once #27 is merged.

**Comment by krystianity** [comment]
Hey guys, any updates on this? Since #27 is merged.

**Comment by stephenplusplus** [comment]
@alexander-fenster could you generate us some GAPIC code?

**Comment by alexander-fenster** [comment]
Working on it.

**Comment by alexander-fenster** [comment]
Will do that.

**Comment by sduskis** [comment]
@alexander-fenster, what's the story with admin?

**Comment by alexander-fenster** [comment]
In progress. Changes will likely be published to googleapis/googleapis
today and then I'll generate the code.
