### ISSUE TITLE
Add OpenCensus sample

### ISSUE THREAD

**Issue by sduskis** [googleapis/nodejs-bigtable#260]
[OpenCensus](http://opencensus.io/) allows users to collect statistics and traces from the client and send them to some service like [Stackdriver](https://github.com/census-instrumentation/opencensus-node/tree/master/examples/grpc).

Cloud Bigtable should have an example that uses tracing and statistics with Stackdriver.

**Comment by mf2199** [comment]
@sduskis The example link seems to be broken.

**Comment by sduskis** [comment]
@mf2199, I updated the link

**Comment by JustinBeckwith** [comment]
This isn't something we plan to do anytime soon, so I'm just closing this out.
