### ISSUE TITLE
The API document page for Filter does not exist

### ISSUE THREAD

**Issue by DominicKramer** [googleapis/nodejs-bigtable#296]
The Filter documentation doesn't exist at [https://cloud.google.com/nodejs/docs/reference/bigtable/0.15.x/Filter](https://cloud.google.com/nodejs/docs/reference/bigtable/0.15.x/Filter).

In addition, Filter is not listed as a class on the main doc page at [https://cloud.google.com/nodejs/docs/reference/bigtable/0.15.x/](https://cloud.google.com/nodejs/docs/reference/bigtable/0.15.x/).

**Comment by sduskis** [comment]
This is a duplicate of #118
