### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by mgarolera** [googleapis/nodejs-bigtable#333]
Users were very confused by the following error message:

(using npm's "@google-cloud/bigtable": "^0.11.1":

{"code":504,"metadata":{"_internal_repr":{...}}}
Error: Error while reading table 'projects/.../instances/.../tables/...'
    at ClientReadableStream._emitStatusIfDone (/usr/src/app/node_modules/@google-cloud/bigtable/node_modules/grpc/src/client.js:255:19)
    at ClientReadableStream._receiveStatus (/usr/src/app/node_modules/@google-cloud/bigtable/node_modules/grpc/src/client.js:233:8)

It is not clear what is the cause of the error. The 504 code should be mapped to Deadline exceeded.

**Comment by sduskis** [comment]
I think that we improved this in newer versions, once we started using GAPIC.  We'll have to check on that, tough.

**Comment by sduskis** [comment]
@stephenplusplus, do you know about 504 error code mapping?

**Comment by callmehiphop** [comment]
@sduskis The common-grpc lib mapped grpc codes to http codes, but gax does no such conversion. I think we should be able to safely close this out.
