### ISSUE TITLE
Empty column qualifiers should not be rejected

### ISSUE THREAD

**Issue by dmmcerlean** [googleapis/nodejs-bigtable#343]
Relevant code is here for reads: https://github.com/googleapis/nodejs-bigtable/blob/13e3d769/src/chunktransformer.js#L251

It's completely valid to use a column like "fam:" which has no qualifier

**Comment by sduskis** [comment]
@muraliQlogic, can you please take a look?

**Comment by sduskis** [comment]
@dmmcerlean "fam":"" is fine, but "fam":[null] is not ok.  I believe the if statement checks for "fam":[null] rather than "fam":"".  We should add a unit test to confirm that.
