### ISSUE TITLE
Convert library to TypeScript

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-bigtable#427]
This needs to happen in steps:
- [x] Rename all the files to `*.ts` and introduce a compile step
- [x] Get the linter and formatter working
- [ ] Enable noImplicitAny and types for all src/ files
- [ ] Update the package.json to ship the types
- [ ] Enable noImplicitAny everywhere

**Comment by JustinBeckwith** [comment]
@joecervino 👋 I think this is the last one :)  I did the initial setup and such!

**Comment by joecervino** [comment]
@JustinBeckwith sounds good, ill get to it asap 👍

**Comment by JustinBeckwith** [comment]
lol
