### ISSUE TITLE
Support GTS lint formatting

### ISSUE THREAD

**Issue by joecervino** [googleapis/nodejs-bigtable#447]
`tslint.json` has the following rules overriding extended `gts` lint/formatting rules:
```
{
  "extends": "gts/tslint.json",
  "rules": {
    "only-arrow-functions": false,
    "no-any": false,
    "no-unused-expression": false,
    "variable-name": false,
    "switch-default": false,
    "ban": false
  }
}
```

The goal is to, one by one file per file, reactivate these rules by refactoring the library to clear errors, leaving the following `tslint.json`: 
```
{
  "extends": "gts/tslint.json",
}
```

Tracking:
- [ ] `only-arrow-functions`
- [ ] `no-any`
- [ ] `no-unused-expression`
- [ ] `switch-default`
- [ ] `variable-name`
- [ ] `ban`

Related to #427 and #445

**Comment by JustinBeckwith** [comment]
This is in good shape
