### ISSUE TITLE
Cancelling a read row stream doesn't cancel the underlying grpc stream

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/nodejs-bigtable#506]
This is copied from a stackoverflow question:

https://stackoverflow.com/questions/56918799/how-to-manually-end-stream-created-by-tablecreatereadstream

> I want to process data from BigTable table in a stream, but end stream early. I am using this code for Node.js (slightly modified https://github.com/googleapis/nodejs-bigtable/blob/master/samples/document-snippets/table.js#L215):

```javascript
const stream = new BigTable({projectId, keyFilename})
  .instance(instanceId)
  .table(tableName)
  .createReadStream();
stream.on('data', () => {
  stream.end();
});
stream.on('end', () => {
  console.log('end');
  stream.destroy();
});
stream.on('close', () => {
  console.log('close');
});
```

Output is:
```javascript
end
close
```

But the process is not yet finished. So, i believe that some resources are not closed. How should i stop stream and close relevant resources?

**Comment by stephenplusplus** [comment]
Thanks for reposting. I'll take a look into this.

**Comment by stephenplusplus** [comment]
I put together a gist to try to reproduce: https://gist.github.com/stephenplusplus/a4e158c3d625f0cd08c0af77937e79c0.

So far, it seems to be working as intended; exiting the process after the stream is ended. Hopefully the StackOverflow author will visit here to clarify.

**Comment by McMerph** [comment]
Hello, i am the author of the StackOverflow question.

Provided gist use table with 50 rows.
I created a new table and inserted 50 rows into it.
Then i measured the time between `table.createReadStream()` and process exit. It was: 289.20 ms
Then i increased number of rows: 50 -> 100 * 1000. Time is: 45321.38 ms
So, it seems that more than one row is processed, although `stream.end()` has been called on first row.
Is it intended behaviour?

**Comment by stephenplusplus** [comment]
It is definitely not intended, and thank you for making the change to highlight the issue. I'll keep looking into it and keep you posted.

**Comment by stephenplusplus** [comment]
I updated the test with your changes, but couldn't see the problem appear yet. Could you make any more required changes?

Gist: https://gist.github.com/stephenplusplus/a4e158c3d625f0cd08c0af77937e79c0

My output:

```
1562691202741 'Starting stream.'
1562691202819 'Data event. stream.end()'
1562691202820 'End event received.'
```

The process then exited.

The whole test takes longer due to the increase in rows being inserted, but the stream calls themselves don't seem to be affected.

**Comment by igorbernstein2** [comment]
@stephenplusplus can you try increasing row size? The current workload will only generate 1 or 2 ReadRowsResponse messages so the additional processing after close might not be evident. Updating the dataset so that a full scan would yield a gigabyte and aborting so that only a few bytes are processed should make this more evident.

**Comment by McMerph** [comment]
Your log end event of stream instead of process exit.

To reproduce issue:
Comment line 38 (remove test resources manually after test).
Add `process.on('exit', () => { console.log(Date.now()); });`
Then run with 50 and 100 * 1000 rows (line 15) and measure execution time.

**Comment by McMerph** [comment]
@igorbernstein2 I don't think than there is a need to increase row size. In fact, i tested it with smaller key size but with different values for keys.

**Comment by McMerph** [comment]
I created my version of test to not wait for table creation on each run: https://gist.github.com/McMerph/b887b4bfbbb94b2a30c14c73accd6003
There should be a huge difference in execution times of `test-small` and `test-big`.
For me it was 3643.92 ms vs 37068.58 ms.

**Comment by stephenplusplus** [comment]
Thank you! I was able to reproduce the issue using your gist. I have a fix in the works, which involves cancelling the underlying request stream when the user ends the stream.

**Comment by stephenplusplus** [comment]
I sent a PR in #507.
