### ISSUE TITLE
Table Row mutation use Admin API?

### ISSUE THREAD

**Issue by nodeful** [googleapis/nodejs-bigtable#54]
Today I was playing around with this Library and noticed that it ate up all my BigTable Admin API quota, while I was inserting rows into a pre-created table. 
Shouldn't any row mutation be performed through the BigTable API that doesn't have a quota? 
I am running a Development BigTable instance at the moment.

#### Environment details

  - OS: Alpine
  - Node.js version: 8.9
  - npm version: 5.5
  - @google-cloud/bigtable version: 0.11.1

#### Steps to reproduce

```js
const bigtable = new BigTable({
  projectId: process.env.GCLOUD_PROJECT,
  credentials: JSON.parse(process.env.BIGTABLE_SERVICE_ACCOUNT) // BigTable User service account
})
const instance = bigtable.instance('my-instance')
const table = instance.table('my-table')

for (var i = 0; i < 1000; i++) { // 7000 is the daily quota limit on Admin API Table Writes
  table.insert([{
     key: 'my-key-' + i, 
     data: { 
       family { 
         column: i
       }
     }
  }])
}
  
```

**Comment by stephenplusplus** [comment]
@kolodny @sduskis any insight on this? The currently released version of this library calls "BigtableClient"'s "mutateRows" rpc.

**Comment by sduskis** [comment]
@stephenplusplus, I'm guessing that this isn't a problem with `mutateRows`.  Is it possible that these two lines run any RPCs?

```
const instance = bigtable.instance('my-instance')
const table = instance.table('my-table')
```

**Comment by sduskis** [comment]
@nodeful, can you please create a support ticket?  That would help us deep dive into this problem.

**Comment by stephenplusplus** [comment]
I'm going to close this here for now, but we can re-open if anything comes of the investigation to suggest we can resolve on our end.

**Comment by nodeful** [comment]
I think some of the merges into this repo: https://github.com/stephenplusplus/google-auto-auth/pulls
fixed the problem for me. All I had to do is `npm i -S @google-cloud/bigtable` again. This pulled the latest google-auto-auth and saved in package-lock.json
