### ISSUE TITLE
remove common-grpc logic that could be pulled in to gax

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-bigtable#556]
This is a follow up to @alexander-fenster's comments:

https://github.com/googleapis/nodejs-bigtable/pull/554/files#r333816049, and
https://github.com/googleapis/nodejs-bigtable/pull/554/files#r333816370

On #554, I suggested that we pull in logic identical to `@google-cloud/common-grpc`, but work towards refactoring this out in future PRs (perhaps pulling more of the logic into `gax`).

**Comment by meredithslota** [comment]
@kolea2 Possibly a good clean-up project to prioritize in 2022?

**Comment by danieljbruce** [comment]
The entire `decorateStatus.ts` file seems to be gone so I am guessing this was cleaned up long ago.
