### ISSUE TITLE
Supporting KeyOnlyFilter

### ISSUE THREAD

**Issue by daneshka** [googleapis/nodejs-bigtable#557]
Based on [this doc](https://cloud.google.com/bigtable/docs/hbase-differences) KeyOnlyFilter is supported in bigtable and I can also see [Java samples](https://github.com/googleapis/googleapis/blob/master/google/bigtable/admin/v2/bigtable_table_admin.proto)
But I can't find it in the nodejs library/document.
It would be great to have this filter in the nodejs library as well.

**Comment by crwilcox** [comment]
The hello world sample for Node.js at https://cloud.google.com/bigtable/docs/samples-nodejs-hello#creating-filter shows how to use filters. Is this what you are looking for?

**Comment by daneshka** [comment]
I tried filters but in my case, I just want to get the key.
When I exclude all of the columns by filters, it returns nothing.
I'm not sure is there any other way to get the key only by a filter.

**Comment by callmehiphop** [comment]
I'm definitely not a Bigtable expert, but it doesn't look like they offer that filter in the actual Bigtable API. My best guess would be to use the `strip_value_transformer` filter and just map the row keys.

```js
const filter {
  value: {strip: true}
};

const [rows] = await table.getRows({filter});
const keys = rows.map(row => row.id);
```

**Comment by daneshka** [comment]
Thank you @callmehiphop 
That's what I was looking for.

**Comment by callmehiphop** [comment]
@daneshka awesome, glad I could help!
