### ISSUE TITLE
Issue installing on Node 8.12.0

### ISSUE THREAD

**Issue by wyardley** [googleapis/nodejs-bigtable#560]
## Environment details

  - OS: Linux
  - Node.js version: v8.12.0
  - npm version: 6.4.1
  - `@google-cloud/bigtable` version: 2.2.1

#### Steps to reproduce

  1. Install `@google-cloud/bigtable@2`
  2. Run a test that imports the library. Error given is:
```
  Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0
```

The breaking change mentioned in the changelog (https://github.com/googleapis/nodejs-bigtable/blob/master/CHANGELOG.md#-breaking-changes) updates the engines field to >= 8.10.0. However, it seems like a subdep here does not support it.

**Comment by bcoe** [comment]
@wyardley sorry about this confusion, I think we should update our engines field accordingly. `@grpc/grpc-js` is a critical dependency, and it sounds like we should instead indicate that `8.13.0` is our minimum required version of Node.

**Comment by stephenplusplus** [comment]
@bcoe should we kick off a super-PR to update that across the repos?

**Comment by stephenplusplus** [comment]
@bcoe I forget if we had a reason to wait on this. Should we do the super PR?

**Comment by stephenplusplus** [comment]
Status: We are going to check back up on this in early December.

**Comment by JustinBeckwith** [comment]
About to drop support for 8 all together, so I guess it kind of took care of itself
