### ISSUE TITLE
getInstances type is incorrect: returns a Promise when callback is unspecified

### ISSUE THREAD

**Issue by lukasschwab** [googleapis/nodejs-bigtable#564]
#### Environment details

  - OS: macOS 10.14
  - Node.js version: v12.12.0
  - npm version: 6.11.3
  - `@google-cloud/bigtable` version: 2.2.1

#### Steps to reproduce

I have code that calls `getInstances` without defining a callback:

```ts
const [instances] = await bigtable.getInstances();
```

`getInstances` behaves according to its docstring:

> If the callback is omitted, we'll return a Promise.

...but this behavior is not reflected in its generated type, which has return type `void` and no overloads:

```ts
getInstances(gaxOptions?: any, callback?: any): void;
```

This mismatch causes eslint to complain because `void` is a non-Promise.

![Screen Shot 2019-11-07 at 15 44 55](https://user-images.githubusercontent.com/4955943/68437373-9ae93e80-0175-11ea-9ba1-15ab13bd9684.png)

#### Proposal

Declare an overload type:

```typescript
getInstances(gaxOptions?: any, callback: any): void;
getInstances(gaxOptions?: any): Promise<Instance[]>;
```

Thanks!

**Comment by jkwlui** [comment]
We need to annotate this client like the way we do with other TypeScript libraries.

**Comment by lukasschwab** [comment]
@jkwlui can you link one of the annotated libraries/documentation for the annotation style? I'd be happy to give it a shot this weekend.

**Comment by callmehiphop** [comment]
@JustinBeckwith @jkwlui looks like we're missing types across the board for the entire client. Is this something that is being prioritize? There isn't an open issue or anything, but I'd be happy to try and take this if some one isn't already.

**Comment by bcoe** [comment]
@callmehiphop could we leverage @alexander-fenster's work to auto-generate types with the new micro-generator?

**Comment by callmehiphop** [comment]
@bcoe it would help in some aspects like having request/response types mapped out for us.

**Comment by xiaowei-routific** [comment]
We are currently adopting bigtable right now and having the same problem.  We have a thin layer of wrapper of our own right now and really hope that this could be prioritized

**Comment by jgehrcke** [comment]
Can we do the same for `createInstance` and other entry points?
