### ISSUE TITLE
Snippets are missing from API reference docs.

### ISSUE THREAD

**Issue by frankyn** [googleapis/nodejs-bigtable#566]
@bcoe created a new plugin jsdoc-region-tag.

Snippets are missing from API reference docs and was surfaced by @billyjacobson.

**Comment by bcoe** [comment]
we will get `jsdoc-region-tag` tested on some libraries next week, I'll also work on an Ariane launch for it.

**Comment by billyjacobson** [comment]
Thanks for helping out with this guys :)
