### ISSUE TITLE
One-off issue in conversion of INT64 to number

### ISSUE THREAD

**Issue by david-cannady** [googleapis/nodejs-bigtable#575]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-bigtable/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: MacOS 10.4, Windows 10
  - Node.js version: !2.3.1
  - npm version: 6.10.2
  - `@google-cloud/bigtable` version: 1.0.1

#### Steps to reproduce

  1. Set an Integer column to Number.MIN_SAFE_INTEGER  or Number.MAX_SAFE_INTEGER, via some other method
  2. Attempt to read the value. Using this library
  3. See that the value returned is a string.

Source: https://github.com/googleapis/nodejs-bigtable/blob/1cb65a47553ab93572bfd95825074ab362ecd9f8/src/mutation.ts#L114
This line should read 
```
if (Number.MIN_SAFE_INTEGER <= num && num <= Number.MAX_SAFE_INTEGER) {
```
to include the SAFE_INTEGER bounds.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by stephenplusplus** [comment]
Nice find! Thank you! Feel free to take a shot at a pull request, otherwise we should have this taken care of soon. Thanks again for pointing this out!
