### ISSUE TITLE
Overwriting row cell data

### ISSUE THREAD

**Issue by omrib15** [googleapis/nodejs-bigtable#700]
Hey, I'm trying to update an existing row's data. I'm using table's insert method with a new row object that has the same key as an existing row. This doesn't overwrite, but adds another row under the same key. 

What's the best way to overwrite existing rows? I don't want to delete the old row first and then insert the new row, since this will slow the entire process.

**Comment by AVaksman** [comment]
@omrib15 thank you for inquiring

- The data in Cloud Bigtable structured so, that a cell can have multiple versions of the value differentiated by cell's timestamp. ([doc](https://cloud.google.com/bigtable/docs/garbage-collection#timestamps))
- The amount of data stored (number of cell's versions or cell's value age) can be regulated by various types of the garbage collection rules ([doc](https://cloud.google.com/bigtable/docs/garbage-collection#types)). However it can take up to a week for data that is eligible for garbage collection to be removed. ([doc](https://cloud.google.com/bigtable/docs/garbage-collection#overview)).

There are couple of ways to read or keep the latest data.
1. You could utilize a filter to return only the most recent cell value vs the full historic data.
```ts
const [rows] = await table.getRows({
  filter: {
    column: {
      cellLimit: 1,
    },
  },
});
```

You can find more useful filter samples [here](https://cloud.google.com/bigtable/docs/using-filters#node.js_2)

2. Always override the existing cell data. ([doc](https://cloud.google.com/bigtable/docs/gc-latest-value))
Set the timestamp to zero every time the data is written.
```ts
const row = {
  key: 'Smith',
  data: {
    address: {
      street: {
        value: 'Main',
        timestamp: new Date(0),
      },
    },
  },
};
// Insert the original row
await table.insert(row);

const updatedRow = {
  key: 'Smith',
  data: {
    address: {
      street: {
        value: 'First',
        timestamp: new Date(0),
      },
    },
  },
};
// Update/override data of the existing row
await table.insert(updatedRow);
```

Please confirm if it answers your question.
