### ISSUE TITLE
Default credentials error while using with a Bigtable emulator

### ISSUE THREAD

**Issue by przemekd** [googleapis/nodejs-bigtable#75]
I try to use this library with a Bigtable emulator. Everything I try to do ends with an error:
`Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
`

#### Environment details

  - OS: Ubuntu 16.04
  - Node.js version: v6.14.1
  - npm version: 3.10.10
  - `@google-cloud/bigtable` version: 0.13.0

#### Steps to reproduce

  1. Download install and run Bigtable emulator.
  2. Export env variable using: ` $(gcloud beta emulators bigtable env-init)`
  3. Run an example: `node example.js`

```javascript
const Bigtable = require('@google-cloud/bigtable');

var client = new Bigtable.v2.BigtableTableAdminClient();

client.createTable("test").then().catch(function (err) {
    console.log(err)
})
```

**Comment by stephenplusplus** [comment]
That path, `Bigtable.v2.BigtableTableAdminClient()` takes you right to the "GAPIC" layer, which is an autogenerated client. The handwritten layer stands in front of that. The same operation should look like:

```js
const Bigtable = require('@google-cloud/bigtable');

var client = new Bigtable();
var instance = client.instance('instance-name'); // doesn't have to be created (see link below)
instance.createTable('test');
```

The local emulator will be recognized and used.

> The emulator does not provide administrative APIs to create or manage instances and clusters. After the emulator starts up, you can connect to it using any project and instance name to create tables and read or write data.
> \- https://cloud.google.com/bigtable/docs/emulator

**Comment by przemekd** [comment]
@stephenplusplus The same happens with your code:
`(node:2139) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
`

**Comment by stephenplusplus** [comment]
Can you verify the correct environment variables are set, given from the emulator? I tested locally before sharing the code, and it worked for me.

**Comment by przemekd** [comment]
Yep, there is a variable set by a gcloud command:

```
$ env | grep -i bigtable
BIGTABLE_EMULATOR_HOST=localhost:8086
```

**Comment by stephenplusplus** [comment]
I was able to reproduce. I should have a PR tomorrow.

**Comment by stephenplusplus** [comment]
@przemekd PR is ready for review! Feel free to check it out, or just try it:

```sh
$ npm install --save stephenplusplus/nodejs-bigtable#spp--75
```

**Comment by przemekd** [comment]
@stephenplusplus Thanks a lot, it works now. :+1:

**Comment by stephenplusplus** [comment]
That's good news! We haven't merged to master yet, so we'll keep the issue open for now :)
