### ISSUE TITLE
Some numbers not decoded

### ISSUE THREAD

**Issue by pkriete** [googleapis/nodejs-bigtable#76]
We just upgraded to 0.13 from 0.11 and are seeing a regression with `decode: true`.

One of our numeric values is being decoded while in a `ROW_IN_PROGRESS` state in the ChunkTransformer [here](https://github.com/googleapis/nodejs-bigtable/blob/master/src/chunktransformer.js#L332). Passing `isPossibleNumber: true` fixes the problem, but I'm not sure what other side effects that might have.

Happy to outline more of what we're doing if that helps narrow it down. Thanks!

**Comment by stephenplusplus** [comment]
@kolodny -- any ideas?

**Comment by sduskis** [comment]
@ajaaym

**Comment by kolodny** [comment]
It's always safe to pass true in, it's only there for performance
considerations. If it needs to be changed to true then by all means change
it where needed
