### ISSUE TITLE
Bigtable error silently ignored

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/nodejs-bigtable#8]
_From @kolodny on November 5, 2017 17:59_

  - OS: OSX 10.12.6
  - Node.js version: 8.5.0 and 6.x
  - npm version: 5.3.0
  - google-cloud-node version: bigtable@0.10.2 common-grpc@0.4.2 retry-request@3.1.0

#### Steps to reproduce

```js
const bigtable = require('@google-cloud/bigtable');

const bigtableClient = bigtable();
const instance = bigtableClient.instance(process.env.INSTANCE_ID);
const table = instance.table('doesnotexist');

Promise.resolve()
  .then(() => table.getRows())
  .then(([rows]) => console.log(`Read ${rows.length}`))
  .catch(error => console.error(`caught ${error}`))
```

I chased this bug down to https://github.com/GoogleCloudPlatform/google-cloud-node/blob/a64ad81517045196cf5a3f468ea15aad1e2c25da/packages/common-grpc/src/service.js#L376-L385

This "fake" response call causes [`streamResponseHandled` in `retry-request` to be set to true on the fake response](https://github.com/stephenplusplus/retry-request/blob/4181eec8187c3603d4e4e68db1ee6ac27725afa3/index.js#L113-L133), that has the consequence of never firing the error callback. https://github.com/stephenplusplus/retry-request/blob/4181eec8187c3603d4e4e68db1ee6ac27725afa3/index.js#L113-L133

I tried reverting the code in #1444 to see if I could replicate the bug referenced at #1443 to see if I could find a different solution that would avoid this nasty regression, but I wasn't able to repro (I always got a response). I suspect that the code can be safely reverted. **Reverting that bit of code did fix the bug of silently ignoring erorrs!**

Thanks!

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#2724_

**Comment by callmehiphop** [comment]
This is a `common-grpc` issue. Re-opening the original.
