### ISSUE TITLE
When multiple cell exists in one column, second element of ICellChunk[] doesn't have enough data.

### ISSUE THREAD

**Issue by takaaki7** [googleapis/nodejs-bigtable#810]
When multiple cell exists in one column, second element of ICellChunk[] doesn't have `rowKey`, `qualifier` and `familyName`.
#### Environment details

  - OS: any
  - Node.js version: v12.16.0
  - npm version: 6.13.4
  - `@google-cloud/bigtable` version: 2.3.2

#### Steps to reproduce

  1. write some data twice into one cell.
  2. call readRows to read that row.

column state.
```
somekey
  v:value                                  @ 2020/10/08-23:59:23.038000
    "[]"
  v:value                                  @ 2020/10/08-23:59:22.774000
    "[]"
```

readRows code.
```js
this.client.readRows({
      tableName: this.formattedTableName,
      rows: ["somekey"],
     })
     .on("data", (res: ReadRowsResponse) => {
        console.log(JSON.stringify(res.chunks))
     })
```

output log. Second element of ICellChunk[] doesn't have `rowKey`, `qualifier` and `familyName`.

```
[
  {
    "labels": [],
    "rowKey": {
      "type": "Buffer",
      "data": [
        57,
        54,
        49,
//....
      ]
    },
    "familyName": {
      "value": "v"
    },
    "qualifier": {
      "value": {
        "type": "Buffer",
        "data": [
          118,
          97,
          108,
          117,
          101
        ]
      }
    },
    "timestampMicros": "1602169163707000",
    "value": {
      "type": "Buffer",
      "data": [
        91,
        93
      ]
    },
    "valueSize": 0
  },
  {
    "labels": [],
    "rowKey": {
      "type": "Buffer",
      "data": []
    },
    "familyName": null,
    "qualifier": null,
    "timestampMicros": "1602169162907000",
    "value": {
      "type": "Buffer",
      "data": [
        91,
        93
      ]
    },
    "valueSize": 0,
    "commitRow": true,
    "rowStatus": "commitRow"
  }
]
```

**Comment by laljikanjareeya** [comment]
@takaaki7 Thanks for the report. This is actual Response comes from back-end.

In your case if you are reading rows from table we recommended to use [createReadStream](https://googleapis.dev/nodejs/bigtable/latest/Table.html#createReadStream) or [getRows](https://googleapis.dev/nodejs/bigtable/latest/Table.html#getRows) from `table` as it has wrapper on `readRows`.

Here is code snippet for same:

```ts
    const bigtable = new Bigtable();
    const instance = bigtable.instance('your-instance');
    const table = instance.table('your-table');
    await table
        .createReadStream()
        .on('error', err => {
            // Handle the error.
            console.log(err);
        })
        .on('data', row => {
            console.log(row.id, row.data)
        })
        .on('end', () => {
            // All rows retrieved.
        });
```

**Comment by AVaksman** [comment]
@takaaki7 

Please use functions suggested by @laljikanjareeya in the comment [above](https://github.com/googleapis/nodejs-bigtable/issues/810#issuecomment-718405994).

Depending on various combinations of the fields that are returned on a given `CellChunk` a determination could be made whether the current `CellChunk` is 

- Initial chunk for the rowKey
- continuation of the same rowKey as previous chunk
- continuation of the same column family as previous chunk
- continuation of the same column as previous chunk
- continuation of the previous cell as previous chunk

You can read more documentation [here](https://cloud.google.com/bigtable/docs/reference/data/rpc/google.bigtable.v2#google.bigtable.v2.ReadRowsResponse.CellChunk)

But again, functions offered by the API ([createReadStream](https://googleapis.dev/nodejs/bigtable/latest/Table.html#createReadStream) or [getRows](https://googleapis.dev/nodejs/bigtable/latest/Table.html#getRows)) do all that logic internally.

Please confirm if this answers your question.

**Comment by takaaki7** [comment]
I understood. Thank you!
