### ISSUE TITLE
Refactor backup.ts instance name configuration

### ISSUE THREAD

**Issue by kolea2** [googleapis/nodejs-bigtable#870]
See https://github.com/googleapis/nodejs-bigtable/pull/863#discussion_r625252289 for more details

**Comment by stephenplusplus** [comment]
I left a comment within that thread to keep the context and have the original participants involved.

**Comment by stephenplusplus** [comment]
Closing per https://github.com/googleapis/nodejs-bigtable/pull/863#discussion_r660863601.
