### ISSUE TITLE
Double values in a cell are not read correctly

### ISSUE THREAD

**Issue by varundhussa** [googleapis/nodejs-bigtable#877]
#### Environment details

  - OS: Linux
  - Node.js version: v12.21.0
  - npm version: 7.5.2
  - `@google-cloud/bigtable` version: 

#### Steps to reproduce

  1. Write a double value byte array to a Bigtable column using Java/Python
  2. Read the column value using the node client library
  3. Convert the result byte string to double using Buffer.from(bytestring).readDoubleBE()

Making sure to follow these steps will guarantee the quickest resolution possible.

The following test for the Mutation will fail:

         var view = new DataView(new ArrayBuffer(8));
         view.setFloat64(0, Math.PI);
         const encoded = Buffer.from(view.buffer).toString('base64');
         const decoded = Mutation.convertFromBytes(encoded, {isPossibleNumber: true,});
 
         assert.strictEqual(Math.PI, decoded);

Long type is returned after conversion. Other numeric types should follow the same pattern.

Thanks!

**Comment by crwilcox** [comment]
Thanks for filing @varundhussa . I have left some comments on your PR. 

Also, is the sample a 'realistic' one, or just to demonstrate the problem?

**Comment by crwilcox** [comment]
@varundhussa what is the current behavior when that code is run? What is the output?

**Comment by meredithslota** [comment]
Closing, not enough info to debug. Also closing open linked PR.
