### ISSUE TITLE
Problem with boolean and decimal values

### ISSUE THREAD

**Issue by moander** [googleapis/nodejs-bigtable#89]
I'm seeing this result. bool and bool_t should be true, bool_f should be false, and dec should be 1.23

```js
{
  "id": "gwashington",
  "data": {
    "fam1": {
      "bin": [
        {
          "value": "abc",
          "labels": [],
          "timestamp": "1523953458013000"
        }
      ],
      "bool": [
        {
          "value": "",
          "labels": [],
          "timestamp": "1523953458013000"
        }
      ],
      "bool_f": [
        {
          "value": "",
          "labels": [],
          "timestamp": "1523953458013000"
        }
      ],
      "bool_t": [
        {
          "value": "",
          "labels": [],
          "timestamp": "1523953458013000"
        }
      ],
      "dec": [
        {
          "value": 1,
          "labels": [],
          "timestamp": "1523953458013000"
        }
      ],
      "jadams": [
        {
          "value": 1,
          "labels": [],
          "timestamp": "1523953458013000"
        }
      ],
      "str": [
        {
          "value": "hello",
          "labels": [],
          "timestamp": "1523953458013000"
        }
      ]
    }
  }
}
```

#### Environment details

  - OS: macos 10.13.3
  - Node.js version: 8.10.0
  - npm version: 5.6.0
  - yarn version: 1.3.2
  - google-cloud-node version: master branch (0.13)

#### Steps to reproduce

```js
    const entries = [
        {
          method: 'insert',
          key: 'gwashington',
          data: {
            fam1: {
                jadams: 1,
                bool: true,
                bool_t: true,
                bool_f: false,
                dec: 1.23,
                str: "hello",
                bin: Buffer.from('abc'),
            }
          }
        }
      ];

    await table.mutate(entries);
```

**Comment by stephenplusplus** [comment]
I was able to reproduce.

cc @kolodny

**Comment by kolodny** [comment]
Bigtable stores all it's fields in binary with no encoding information. The typical way to put data inside bigtable or extract it out is by manually doing the encoding/decoding. The library currently helps out by [converting numbers to Buffers](https://github.com/googleapis/nodejs-bigtable/blob/master/src/mutation.js#L87-L101) otherwise it just passes whatever the value is to `Buffer.from` and hopes for the best. Ideally every field should be encoded before being passed to `table.mutate`.

In the future we may consider allowing passing some Mutation like API to simplify the encoding/decoding actions to and from the table

**Comment by kolodny** [comment]
One thing to note based on the above, any data previously entered in that fashion should be considered bad and should be deleted

I'll close this issue for now, feel free to reopen if you have any followup questions or issues

**Comment by moander** [comment]
Thanks. I would consider throwing on everything except string buffer and null/undefined instead of potentially storing bad values. After testing to see that string/int works you may move on thinking that also bool and decimal works (like I almost did). 

An option that enables the lib to use JSON.parse() and JSON.stringify() on non-buffer values could be handy.

```js
JSON.parse(JSON.stringify(null)) // returns null
JSON.parse(JSON.stringify(1.23)) // returns 1.23
JSON.parse(JSON.stringify(new Date())) // returns string 2018-04-22T05:04:10.213Z
JSON.parse(JSON.stringify(true)) // returns true
JSON.parse(JSON.stringify('')) // returns ''
JSON.parse(JSON.stringify(undefined)) // fails
```

**Comment by kolodny** [comment]
Thanks @moander, I opened #102 to get a discussion about that point started.
