### ISSUE TITLE
getTables returns empty metadata.columnFamilies object

### ISSUE THREAD

**Issue by moander** [googleapis/nodejs-bigtable#91]
table.get() returns the families but the object is empty using getTables

```
t1 { AutoCreateFamily: { gcRule: null } }

t2 {}
```

#### Environment details

OS: macos 10.13.3
Node.js version: 8.10.0
npm version: 5.6.0
yarn version: 1.3.2
`@google-cloud/bigtable` version: master branch (0.13)

#### Steps to reproduce

```js
    let [t1] = await table.get();
    console.log('t1', t1.metadata.columnFamilies);

    let [tables] = await bt.getTables();
    let t2 = tables.find(t => t.name === 'TestAutoCreate');
    console.log('t2', t2.metadata.columnFamilies);
```

**Comment by callmehiphop** [comment]
Looks like we're [assigning the metadata](https://github.com/googleapis/nodejs-bigtable/blob/master/src/instance.js#L694) correctly. @sduskis will the column families be returned via `listTables`?

**Comment by sduskis** [comment]
@callmehiphop: Column families are not returned from listTables.  One would have to call GetTable (per table) to populate the column familes.

**Comment by sduskis** [comment]
@stephenplusplus: what do we need to do here?

`GetTables` returns a list of Strings.  Should we deprecate `getTables()` and create a new method called `getTableNames()`?

**Comment by stephenplusplus** [comment]
We call our method `getTables()` because we are returning `Table` objects. Those objects can be used to call `getMetadata()` on for a more complete representation.

**Comment by callmehiphop** [comment]
My guess is that this is something we can resolve with documentation
