### ISSUE TITLE
New patch release

### ISSUE THREAD

**Issue by rlucioni** [googleapis/nodejs-bigtable#92]
Is there any chance you could release an 0.13.1 that includes the changes from https://github.com/googleapis/nodejs-bigtable/pull/77? A release was alluded to in https://github.com/googleapis/nodejs-bigtable/issues/83 but doesn't seem to have happened yet. Thank you!

**Comment by kolodny** [comment]
@stephenplusplus Can we push out a release?

**Comment by stephenplusplus** [comment]
PR sent: #93

**Comment by rlucioni** [comment]
Reopening because 0.13.1 hasn't made it to npm. Looks like the system_tests job failed and prevented the publish_npm job from running.

**Comment by stephenplusplus** [comment]
Now we did it!
