### ISSUE TITLE
row.get() ignores columns array when filters are applied

### ISSUE THREAD

**Issue by moander** [googleapis/nodejs-bigtable#98]
#### Environment details

OS: macos 10.13.3
Node.js version: 8.10.0
npm version: 5.6.0
yarn version: 1.3.2
@google-cloud/bigtable version: master branch (0.13)

#### Steps to reproduce

```js
    const columns = ['fam:col'];
    const options = {
        filter: [
            {
                column: {
                    cellLimit: 1
                }
            },
        ]
    };

    await table.row('key').get(columns); // Returns single column
    await table.row('key').get(columns, options); // Returns all columns
```

**Comment by callmehiphop** [comment]
@moander have you tried using `filter` instead of `filters`?

**Comment by moander** [comment]
@callmehiphop that is actually what I'm doing.. So bad repro code ;)

**Comment by sduskis** [comment]
The code fix: The explicit filter the user passes in has to be "chained" with the filter that results from the columns parameter.

The usage fix: ???  I don't know how to do this now.  I'm going to have to see if it's possible.

**Comment by sduskis** [comment]
This should work for one column:

```
var filter =[
    { family: 'fam },
    { column: 'col' },
    { column: { cellLimit: 1 } }
]
```
This should work for additional column/families

```
var filter =[
    { interleave: [
       [{ family: 'fam1' },{ column: 'col1' }],
       [{ family: 'fam2' },{ column: 'col2' }]
    ]},
    { column: { cellLimit: 1 } }
]
```
